---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoapp-test
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.app: semver:~1.0
    repository.fluxcd.io/app: app.image # image value [ values.app.image ]
    tag.fluxcd.io/app: app.tag # tag value [ values.app.image ]
spec:
  releaseName: echoapp-test
  chart:
    git: git@github.com:nadivravivz/fluxtest.git
    path: charts/ravivecho
    ref: master
  values:
    image:
      repository: nadivravivz/echoapp
      tag: 1.0
    replicaCount: 1
    hpa:
      enabled: false
